/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import qnx.buildfile.lang.buildfileDSL.Model
import java.io.InputStream
import qnx.buildfile.lang.buildfileDSL.AttributeStatement
import qnx.buildfile.lang.buildfileDSL.DeploymentStatement
import qnx.buildfile.lang.buildfileDSL.Statement
import qnx.buildfile.lang.buildfileDSL.Attribute
import qnx.buildfile.lang.buildfileDSL.BooleanAttribute
import qnx.buildfile.lang.buildfileDSL.ValuedAttribute
import qnx.buildfile.lang.buildfileDSL.Content
import qnx.buildfile.lang.buildfileDSL.Path
import qnx.buildfile.lang.buildfileDSL.ContentBlock

@ExtendWith(InjectionExtension)
@InjectWith(BuildfileDSLInjectorProvider)
class BuildfileDSLParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	
	def static String text(InputStream stream) {
        new String(stream.readAllBytes, java.nio.charset.StandardCharsets.UTF_8)
    }
	
	def static String evaluate(Statement statement)
	{
		if (statement instanceof AttributeStatement)
		{
			return (statement as AttributeStatement).evaluate
		}
		else if (statement instanceof DeploymentStatement)
		{
			return (statement as DeploymentStatement).evaluate
		}
	}
	
	def static String evaluate(AttributeStatement attributeStatement)
	{
		var ret = "AttributeStatement\n"
		ret  += attributeStatement.attributesection.attributes.map[evaluate].join("\n")
		return ret
	}
	
	def static String evaluate(DeploymentStatement deploymentStatement)
	{
		var ret = "DeploymentStatement\n"
		
		if (deploymentStatement.attributesection !== null) ret += deploymentStatement.attributesection.attributes.map[evaluate].join("\n")
		ret += '\nPATH: ' + deploymentStatement.path + "\n"
		if (deploymentStatement.isAssignment()) ret += deploymentStatement.assignment + "\n"
		if (deploymentStatement.content !== null) ret += evaluate(deploymentStatement.content) + "\n"
		return ret
		
	}
	
	def static String evaluate(Attribute attribute)
	{
		if (attribute instanceof BooleanAttribute)
		{
			return (attribute as BooleanAttribute).evaluate
		}
		else if (attribute instanceof ValuedAttribute)
		{
			return (attribute as ValuedAttribute).evaluate
		}		
	}
	
	def static String evaluate(BooleanAttribute booleanAttribute)
	{
		 return (booleanAttribute.isEnabled() ? "PLUS" : "MINUS") + " " + booleanAttribute.name
	}
	
	def static String evaluate(ValuedAttribute valuedAttribute)
	{
		return valuedAttribute.name + " = " + valuedAttribute.value
	}
	
	
	def static String evaluate(Content content)
	{
		if (content instanceof Path)
		{
			return (content as Path).value
		}
		else if (content instanceof ContentBlock)
		{
			return (content as ContentBlock).value
		}		
	}
	
	@Test
	def void loadModel() {
		
		val test1file = this.class.getResourceAsStream("test1.build")
		val expected_output_test1file = this.class.getResourceAsStream("expected_output_test1.txt")
		val test1content = test1file.text
		val expected_output_test1content = expected_output_test1file.text
		
		val result = parseHelper.parse(test1content) as Model

		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		
		val test1_content = result.statements.map[evaluate].join("\n")
				
		Assertions.assertEquals(expected_output_test1content,test1_content)
				
	}
	
}
