/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BuildfileDSLStandaloneSetup extends BuildfileDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new BuildfileDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
