/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BuildfileDSLUiModule extends AbstractBuildfileDSLUiModule {

	public BuildfileDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
