/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.validation;

import org.eclipse.xtext.validation.Check;

import qnx.buildfile.lang.attributes.AttributeKeywords;
import qnx.buildfile.lang.buildfileDSL.Attribute;
import qnx.buildfile.lang.buildfileDSL.BuildfileDSLPackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class BuildfileDSLValidator extends AbstractBuildfileDSLValidator {
	
	@Check
	public void checkAttributes(Attribute attribute) {
		if (!AttributeKeywords.ALL_ATTRIBUTE_KEYWORDS
				.contains(attribute.getName()))
		{
			error("Attribute name \"" + attribute.getName() + "\" is not known",
					BuildfileDSLPackage.Literals.ATTRIBUTE__NAME,
					"invalidName");

		}

	}
	
}
