/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ide;


/**
 * Use this class to register ide components.
 */
public class BuildfileDSLIdeModule extends AbstractBuildfileDSLIdeModule {
}
