/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ide;

import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register ide components.
 * <p>
 * Custom validator JAR support is provided by the default
 * {@link qnx.buildfile.lang.validation.SystemPropertyCustomValidatorJarPathProvider}
 * bound via {@code @ImplementedBy} — no explicit binding needed here.
 */
public class BuildfileDSLIdeModule extends AbstractBuildfileDSLIdeModule {

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return BuildfileDSLSemanticHighlightingCalculator.class;
	}
}
