/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import qnx.buildfile.lang.BuildfileDSLRuntimeModule;
import qnx.buildfile.lang.BuildfileDSLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BuildfileDSLIdeSetup extends BuildfileDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BuildfileDSLRuntimeModule(), new BuildfileDSLIdeModule()));
	}
	
}
