/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ide;

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ide.server.codeActions.ICodeActionService2;
import org.eclipse.xtext.ide.server.symbol.DocumentSymbolMapper;
import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

/**
 * Use this class to register ide components.
 * <p>
 * Custom validator JAR support is provided by the default
 * {@link qnx.buildfile.lang.validation.SystemPropertyCustomValidatorJarPathProvider}
 * bound via {@code @ImplementedBy} — no explicit binding needed here.
 */
public class BuildfileDSLIdeModule extends AbstractBuildfileDSLIdeModule {

	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return BuildfileDSLSemanticHighlightingCalculator.class;
	}

	public Class<? extends DocumentSymbolMapper.DocumentSymbolNameProvider> bindDocumentSymbolNameProvider() {
		return BuildfileDSLDocumentSymbolNameProvider.class;
	}

	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return BuildfileDSLResourceDescriptionStrategy.class;
	}

	public Class<? extends ICodeActionService2> bindICodeActionService2() {
		return BuildfileDSLCodeActionService.class;
	}

	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return BuildfileDSLIdeContentProposalProvider.class;
	}
}
