/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import qnx.buildfile.lang.ide.BuildfileDSLQuickfixResolvers;

/**
 * Quick fixes for BuildfileDSL validation issues in Eclipse.
 * <p>
 * Delegates to {@link BuildfileDSLQuickfixResolvers} for the shared
 * suggestion logic (Levenshtein distance matching).
 */
public class BuildfileDSLQuickfixProvider extends DefaultQuickfixProvider {

	@Fix("invalidName")
	public void fixInvalidAttributeName(final Issue issue, IssueResolutionAcceptor acceptor) {
		String badName = BuildfileDSLQuickfixResolvers.extractBadNameFromMessage(issue.getMessage());
		if (badName == null || badName.isEmpty()) {
			return;
		}

		var suggestions = BuildfileDSLQuickfixResolvers.suggestAttributeNames(badName);

		for (var suggestion : suggestions) {
			final String replacement = suggestion.getKeyword();
			acceptor.accept(issue,
					"Change to '" + replacement + "'",
					"Replace unknown attribute '" + badName + "' with '" + replacement + "'",
					null,
					(context) -> {
						context.getXtextDocument().replace(
								issue.getOffset(),
								issue.getLength(),
								replacement);
					});
		}
	}
}
