/*
 * generated by Xtext 2.39.0
 */
package qnx.buildfile.lang.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class BuildfileDSLProposalProvider extends AbstractBuildfileDSLProposalProvider {
}
